### ISSUE TITLE
Exception in thread "INSTRUMENT17" java.lang.RuntimeException: {"error":"timeout"} 

### ISSUE THREAD

**Issue by aashishtyagi** [influxdata/influxdb-java#145]
Hello Guys,

I m evaluating influxdb for our requirement . While inserting the data in influxdb (using REST ) i m facing the issue mention below :+1: 
Exception in thread "INSTRUMENT17" java.lang.RuntimeException: {"error":"timeout"}

at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
at org.influxdb.impl.$Proxy0.writePoints(Unknown Source)
at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:148)
at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:166)
at org.influxdb.impl.BatchProcessor.put(BatchProcessor.java:179)
at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:134)
at com.gs.task.PriceTask.run(PriceTask.java:150)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
gstest.txt

please change the ext of gstest.txt to gstest.zip .

This zip file contains the code that i m using . I m running TestInflux.java file to insert the data .

Please assist .

Regards,
Aashish
[gstest.txt](https://github.com/influxdata/influxdb-java/files/82200/gstest.txt)

**Comment by aashishtyagi** [comment]
One more thing i observed that this failure happens in case of multi threading. If i use one or two thread to insert data then it works fine .

**Comment by majst01** [comment]
Can you please add logging to the influxdb driver with:

influxDB.setLogLevel(InfluxDB.LogLevel.FULL);

and rerun your tests. 
Please do not add zips with source, you can add the code inline in the issue.

**Comment by aashishtyagi** [comment]
Hello Stefan,
Thank you for such quick reply .

I tried  influxDB.setLogLevel(InfluxDB.LogLevel.FULL) But it did not get reproduce as in case of Full debugging the application behave like single threaded application  .
Please check the thread dump i took :
INSTRUMENT10" prio=10 tid=0x00007f3f6c196000 nid=0x1e1c waiting for monitor entry [0x00007f3f3f7f6000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.io.PrintStream.println(PrintStream.java:806)
	- waiting to lock <0x0000000617c1e368> (a java.io.PrintStream)
	at retrofit.Platform$Base$3.log(Platform.java:108)
	at retrofit.RestAdapter.logAndReplaceRequest(RestAdapter.java:444)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:317)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
	at org.influxdb.impl.$Proxy0.writePoints(Unknown Source)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:148)
	at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:166)
	at org.influxdb.impl.BatchProcessor.put(BatchProcessor.java:179)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:134)
	at com.gs.task.PriceTask.run(PriceTask.java:150)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000006177eedb0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

I started 10 thread but all 9 thread gets stuck on monitor mention above in thread dump. This is because, in case of Full debugging there is a System.out.println comes into the picture and println method has a synchronized block so all other thread get stuck on this monitor .  
So if i do Full Debugging (	influxDB.setLogLevel(LogLevel.FULL)) then it beats the purpose of multi threading .
 Error only occur in case  i make the debug level NONE as multiple thread are executing the work concurrently .

Please let me know if you need to know some other information.

Regards,
Aashish

**Comment by jollyblade** [comment]
Hi, I also have encountered the same issue:

ERROR 2016-01-13 07:01:53,655: Could not save influx performance report: timeout
(influx.InfluxService:InfluxService.java:56) [Job monitoring daemon thread]    
java.lang.RuntimeException: timeout

	at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
	at org.influxdb.impl.$Proxy61.writePoints(Unknown Source)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:156)
	InfluxService.saveReport(InfluxService.java:53)


Best,
Marton

**Comment by aashishtyagi** [comment]
Hello Stefan,

I m getting the same error on single threaded program also.
 java.lang.RuntimeException: {"error":"timeout"}

	at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
	at org.influxdb.impl.$Proxy0.writePoints(Unknown Source)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:148)
	at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:166)
	at org.influxdb.impl.BatchProcessor.put(BatchProcessor.java:179)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:134)
	at com.gs.task.PriceTask.run(PriceTask.java:145)
	at java.lang.Thread.run(Thread.java:744)

Regards,
Aashish

**Comment by romansaul** [comment]
Hi, I also see the same error:
```
java.lang.RuntimeException:` {"error":"timeout"}
at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
at org.influxdb.impl.$Proxy77.writePoints(Unknown Source)
at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:161)
```
My setup is multi threaded. Every thread does this:

1. delete an existing measurement
2. create a new point which fails with timeout
3. create many more points successfully

During this influxdb is under heavy write load of about 20 threads doing the algorithm above. I'm using version 2.1 with influxdb from docker image tutum/influxdb:0.10

**Comment by majst01** [comment]
Please use most recent version of influxdb-java which has lots of work done in the connection handling part. If still persit, please reopen this issue.

**Comment by jollyblade** [comment]
Many thanks, we will update, and test.
