### ISSUE TITLE
Feature to allow canceling a query

### ISSUE THREAD

**Issue by billevans1963** [influxdata/influxdb-java#156]
With InfluxDB, if you submit a badly constrained query (e.g. one without time), then it may take minutes or even hours to complete.  It would be wonderful, in these circumstances to be able to cancel it.  

InfluxDB doesn't currenly support canceling a query but that really doesn't matter;  what I want is to stop the client thread getting stuck on the socket like this:

PcapCrawlerAgent-0 id=32 state=RUNNABLE (running in native)
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:170)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at okio.Okio$2.read(Okio.java:137)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
    at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
    at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
    at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:917)
    at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:95)
    at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:902)
    at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:760)
    at com.squareup.okhttp.Call.getResponse(Call.java:274)
    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
    at com.squareup.okhttp.Call.execute(Call.java:81)
    at retrofit.client.OkClient.execute(OkClient.java:53)
    at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
    at org.influxdb.impl.$Proxy41.query(Unknown Source)
    at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:190)

What I would like, is simply a method in the InfluxDBConx to close the socket and, hence, let the thread continue.

Thoughts?

What

**Comment by majst01** [comment]
I would like to see a sample implementation as PR if you have some, actually i have no concrete idea how to implement, thought it would be useful in some cases.

**Comment by jiafu1115** [comment]
@billevans1963   @majst01 it can be set by construtor with new OkHttpClient.Builder().writeTimeout(timeout, unit) or 
new OkHttpClient.Builder().readTimeout(timeout, unit). So I think there is no need for code change. So if no problems, this issue can be closed. WDTY
