### ISSUE TITLE
Unit tests are failing with the following error

### ISSUE THREAD

**Issue by murugavelpsg** [influxdata/influxdb-java#202]
Hello all,

I cloned the influxdb-java repo and did a "mvn test". Unfortunately many tests are failing. Following is one of the tests which fails. I face issues with creating database. I don't face any issues with drop database or queries. Can somebody please help me? 

```
Tests run: 24, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 2.249 sec <<< FAILURE!
testCreateNumericNamedDatabase(org.influxdb.InfluxDBTest)  Time elapsed: 0.012 sec  <<< FAILURE!
java.lang.RuntimeException: {"error":"error parsing query: found NOT, expected ; at line 1, char 20"}
	at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
	at org.influxdb.impl.$Proxy3.query(Unknown Source)
	at org.influxdb.impl.InfluxDBImpl.createDatabase(InfluxDBImpl.java:205)
	at org.influxdb.InfluxDBTest.testCreateNumericNamedDatabase(InfluxDBTest.java:206)
```

**Comment by murugavelpsg** [comment]
Upgraded influx to 1.0 and pulled the latest change. It worked.
