### ISSUE TITLE
results from multiple queries in a single submission can cause errors, related to clustering?

### ISSUE THREAD

**Issue by beckettsean** [influxdata/influxdb-java#210]
When sending 50+ queries in a single HTTP request, the results are not always properly handled.

E.g. submitting a query batch like this:

```
SELECT id,LAST(count) FROM "foo" WHERE job = '<uuid>' AND version = '1' AND id = 'foobar1';
SELECT id,LAST(count) FROM "foo" WHERE job = '<uuid>' AND version = '1' AND id = 'foobar2';
SELECT id,LAST(count) FROM "foo" WHERE job = '<uuid>' AND version = '1' AND id = 'foobar3';
...
SELECT id,LAST(count) FROM "foo" WHERE job = '<uuid>' AND version = '1' AND id = 'foobar49';
SELECT id,LAST(count) FROM "foo" WHERE job = '<uuid>' AND version = '1' AND id = 'foobar50';
SELECT id,LAST(count) FROM "foo" WHERE job = '<uuid>' AND version = '1' AND id = 'foobar51';
```
using `org.influxdb.impl.InfluxDBImpl#query(Query query)` and `influxDB.query(new Query(String.join(";", queries), dbName))` 

results in this return:

```
Your browser sent an invalid request.
</body></html>

java.lang.RuntimeException: <html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>

    at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
    at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
    at org.influxdb.impl.$Proxy43.query(Unknown Source)
    at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:178)
    at com.streamsets.apps.timeseries.backend.InfluxDBTimeSeriesBackend$8.call(InfluxDBTimeSeriesBackend.java:326)
    at com.streamsets.apps.timeseries.backend.InfluxDBTimeSeriesBackend$8.call(InfluxDBTimeSeriesBackend.java:323)
    at com.streamsets.apps.timeseries.excecutor.InfluxDBTimeSeriesExecutor.execute(InfluxDBTimeSeriesExecutor.java:186)
    at com.streamsets.apps.timeseries.excecutor.InfluxDBTimeSeriesExecutor.executeRead(InfluxDBTimeSeriesExecutor.java:160)
    at com.streamsets.apps.timeseries.backend.InfluxDBTimeSeriesBackend.getLatestCounterValues(InfluxDBTimeSeriesBackend.java:323)
    at com.streamsets.apps.timeseries.backend.InfluxDBTimeSeriesBackend.getLatestAggregatedMetrics(InfluxDBTimeSeriesBackend.java:312)
    at com.streamsets.apps.timeseries.rest.MetricsTimeSeriesResource.getLatestAggregatedMetrics(MetricsTimeSeriesResource.java:159)
```

No errors in InfluxDB, and issuing the query batch via CLI returns the expected results. Looks to be a parsing issue with the query returns.

**Comment by beckettsean** [comment]
Further experimentation shows that the OSS version doesn't show this issue. Only queries sent to InfluxEnterprise demonstrate the return parsing issue.

**Comment by majst01** [comment]
So i guess its an issue with this particular influxdb flavour. We have not tests with this version.

**Comment by beckettsean** [comment]
@majst01 I have an update on this, turns out to have been an architectural issue in the end:

"The client talks to influx enterprise through HaProxy and haproxy has a default limitation on url length causing it throw http 400 (bad request). Once we updated haproxy to allow a bigger url, things started working fine."
