### ISSUE TITLE
Incorrect string escaping of \"

### ISSUE THREAD

**Issue by retronym** [influxdata/influxdb-java#269]
Version: influxdb-java 2.5

```java
        InfluxDB influxDB = connectDb();
        BatchPoints points = BatchPoints.database("scala_benchmark").build();
        points.point(Point.measurement("test").addField("sha", "\"\\\"a b\"\\\"").build());
        influxDB.write(points);
```

Without Java escaping, the field value is:

```
"\"a b"\"
```

From the full log below, this is translated to:
```
test sha="\"\\"a b\"\\"" 1484291695021000000
```

I believe this should be:

```
test sha="\"\\\"a b\"\\\"" 1484291695021000000
```
Log:
```
Jan 13, 2017 5:14:55 PM okhttp3.internal.platform.Platform log
INFO: --> POST https://scala-ci.typesafe.com/write?u=scala&p=GQQMUM6XsWirJH&db=scala_benchmark&precision=n&consistency=one http/1.1
Jan 13, 2017 5:14:55 PM okhttp3.internal.platform.Platform log
INFO: Content-Type: text/plain; charset=utf-8
Jan 13, 2017 5:14:55 PM okhttp3.internal.platform.Platform log
INFO: Content-Length: 45
Jan 13, 2017 5:14:55 PM okhttp3.internal.platform.Platform log
INFO: 
Jan 13, 2017 5:14:55 PM okhttp3.internal.platform.Platform log
INFO: test sha="\"\\"a b\"\\"" 1484291695021000000

Jan 13, 2017 5:14:55 PM okhttp3.internal.platform.Platform log
INFO: --> END POST (45-byte body)
Jan 13, 2017 5:14:56 PM okhttp3.internal.platform.Platform log
INFO: <-- 400 Bad Request https://scala-ci.typesafe.com/write?u=scala&p=GQQMUM6XsWirJH&db=scala_benchmark&precision=n&consistency=one (1249ms)
Jan 13, 2017 5:14:56 PM okhttp3.internal.platform.Platform log
INFO: Server: nginx/1.10.1
Jan 13, 2017 5:14:56 PM okhttp3.internal.platform.Platform log
INFO: Date: Fri, 13 Jan 2017 07:14:56 GMT
Jan 13, 2017 5:14:56 PM okhttp3.internal.platform.Platform log
INFO: Content-Type: application/json
Jan 13, 2017 5:14:56 PM okhttp3.internal.platform.Platform log
INFO: Connection: keep-alive
Jan 13, 2017 5:14:56 PM okhttp3.internal.platform.Platform log
INFO: Request-Id: fc7b6228-d95f-11e6-8bf8-000000000000
Jan 13, 2017 5:14:56 PM okhttp3.internal.platform.Platform log
INFO: X-Influxdb-Version: 1.1.1
Jan 13, 2017 5:14:56 PM okhttp3.internal.platform.Platform log
INFO: 
Jan 13, 2017 5:14:56 PM okhttp3.internal.platform.Platform log
INFO: {"error":"unable to parse 'test sha=\"\\\"\\\\\"a b\\\"\\\\\"\" 1484291695021000000': bad timestamp"}

Jan 13, 2017 5:14:56 PM okhttp3.internal.platform.Platform log
INFO: <-- END HTTP (102-byte body)
Exception in thread "main" java.lang.RuntimeException: {"error":"unable to parse 'test sha=\"\\\"\\\\\"a b\\\"\\\\\"\" 1484291695021000000': bad timestamp"}

	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:387)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:247)
	at scala.bench.ResultPersister.main(ResultPersister.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1
```

**Comment by amlozano** [comment]
Same here, I am having problems trying to write a string that contains \\" it seems to be because in org.influxdb.dto.Point, the '\' isn't escaped, although I could be wrong
