### ISSUE TITLE
IllegalCharsetNameException when connecting to InfluxDB

### ISSUE THREAD

**Issue by pimeys** [influxdata/influxdb-java#272]
Hi,

I'm trying to open a connection to InfluxDB with library version 2.5:

``` java
InfluxDBFactory.connect("https://xxx.com/influx", "user", "pass");
```

But this crashes with an exception about an invalid charset name:

```
java.nio.charset.IllegalCharsetNameException: java.nio.charset.CharsetICU[UTF-8]
                      at java.nio.charset.Charset.checkCharsetName(Charset.java:201)
                      at java.nio.charset.Charset.forName(Charset.java:295)
                      at java.net.URLEncoder.encode(URLEncoder.java:57)
                      at org.influxdb.dto.Query.encode(Query.java:107)
                      at org.influxdb.impl.InfluxDBImpl.<clinit>(InfluxDBImpl.java:53)
                      at org.influxdb.InfluxDBFactory.connect(InfluxDBFactory.java:62) 
```

I'm using the library in Android version 6.0.1, Java version 1.7.

**Comment by mnuessler** [comment]
It looks as if on your Android platform the `toString()` method underlying `Charset` class would return the value `java.nio.charset.CharsetICU[UTF-8]` while influxdb-java expects it to return `UTF-8`.

In general it is not a good idea to rely on the return value of a `toString()` method. I created PR #272 that should fix the issue by using `name()` instead. Unfortunately I have no way to verify that it really solves the issue on Android.

**Comment by majst01** [comment]
@pimeys any chance to test @mnuessler fix on you platform, if you can confirm it works i will merge it.

**Comment by pimeys** [comment]
Works, you can merge to master :) Thanks.
