### ISSUE TITLE
Non default port

### ISSUE THREAD

**Issue by jollyblade** [influxdata/influxdb-java#299]
Hi, 

I have an issue running an influx instance on a different port, for example 8080. 
Then the following code throws a connection timeout exception:

`
		InfluxDB influxDB = InfluxDBFactory.connect("http://ing04appdmc05p.media-saturn.com:8080", "dmc", "M0n1t0r1ngX543");
		String dbName = "dmc";

		Point point1 = Point.measurement("cpu").time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
			  .addField("idle", 90L).addField("user", 9L).addField("system", 1L).build();
		Point point2 = Point.measurement("disk").time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
			  .addField("used", 80L).addField("free", 1L).build();

		influxDB.write(dbName, "autogen", point1);
		influxDB.write(dbName, "autogen", point2);
`
I am not sure if the lib takes the port into account, I guess not. 

Best regards, 
Marton

**Comment by jollyblade** [comment]
curl -u usr:pwd -i -XPOST http://host:8080/query --data-urlencode "q=SHOW DATABASES"  works properly

**Comment by majst01** [comment]
You can increase the loglevel with:

```java
influxDB.setLogLevel(LogLevel.FULL)
```

and post the output.

**Comment by jollyblade** [comment]
Hi, 

sure, I changed the url of course:

Mar 21, 2017 3:17:27 PM okhttp3.internal.platform.Platform log
INFO: --> POST http://host:8080/write?u=user&p=pwd&db=db&rp=autogen&precision=n&consistency=one http/1.1
Mar 21, 2017 3:17:27 PM okhttp3.internal.platform.Platform log
INFO: Content-Type: text/plain; charset=utf-8
Mar 21, 2017 3:17:27 PM okhttp3.internal.platform.Platform log
INFO: Content-Length: 51
Mar 21, 2017 3:17:27 PM okhttp3.internal.platform.Platform log
INFO: 
Mar 21, 2017 3:17:27 PM okhttp3.internal.platform.Platform log
INFO: cpu idle=90i,system=1i,user=9i 1490105847386000000

Mar 21, 2017 3:17:27 PM okhttp3.internal.platform.Platform log
INFO: --> END POST (51-byte body)
Mar 21, 2017 3:17:37 PM okhttp3.internal.platform.Platform log
INFO: <-- HTTP FAILED: java.net.SocketTimeoutException: connect timed out

java.lang.RuntimeException: java.net.SocketTimeoutException: connect timed out

	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:390)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:247)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:222)
	at de.mediamarkt.dmc.framework.influx.InfluxServiceSpringManTest.apiTest(InfluxServiceSpringManTest.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:124)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:187)
	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:196)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:132)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:101)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall.execute(RealCall.java:63)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:382)
	... 39 more


Process finished with exit code 255

**Comment by majst01** [comment]
and as you can see it posts to:

```
INFO: --> POST http://host:8080/write?u=user&p=pwd&db=db&rp=autogen&precision=n&consistency=one
```

but you get a 

```
Caused by: java.net.SocketTimeoutException: connect timed out
```

So this is a connection problem, the influxdb-library connects to the given url.

**Comment by jollyblade** [comment]
Yes, I can see that, but the same connection works on my machine with curl, when I am posting directly, so I can connect to it. On the other hand, I debugged a bit, and the following is strange:

 private InetAddress parseHostAddress(String url) {
        try {
            return InetAddress.getByName(**HttpUrl.parse(url).host()**);
        } catch (UnknownHostException var3) {
            throw new RuntimeException(var3);
        }
    }

And of course using the default port, it works just fine. I keep debugging, and if I find something, I will update the thread.

**Comment by jollyblade** [comment]
Okay, it's definitely not the port, I can reproduce the issue with the default port too, I can curl to the instance anything, but I can't connect from java. It works also from the browser. 
I tested with 1.1, 1.2, same problem. The same code works for other instances running on other servers. I have no idea, but the issue is somewhere else, I guess I can close this one.

**Comment by jollyblade** [comment]
It's an issue with the OkHttp, the following code works:

appache http client:

HttpClient httpclient = HttpClients.createDefault();
		HttpPost httppost = new HttpPost("http://host:8086/query");

		// Request parameters and other properties.
		List<NameValuePair> params = new ArrayList<NameValuePair>(2);
		params.add(new BasicNameValuePair("q", "SHOW DATABASES"));
		httppost.setEntity(new UrlEncodedFormEntity(params, "UTF-8"));

		//Execute and get the response.
		HttpResponse response = httpclient.execute(httppost);
		HttpEntity entity = response.getEntity();

		if (entity != null) {
			InputStream instream = entity.getContent();
			try {
				BufferedReader r = new BufferedReader(new InputStreamReader(instream));
				String line;
				while((line = r.readLine())!=null){
					log.debug(line);
				}
			}
			finally {
				instream.close();
			}
		}


the following code doesn't, the same connection timeout occurs. 

//		MediaType formdata = MediaType.parse("application/x-www-form-urlencoded; charset=utf-8");
//		OkHttpClient cl = new OkHttpClient();
//		RequestBody body = RequestBody.create(formdata, "q=SHOW DATABASES");
//		Request request = new Request.Builder().url("http://ing04appdmc05p.media-saturn.com:8086/query").post(body).build();
//		Response response = cl.newCall(request).execute();
//		log.debug(response.body().string());

**Comment by majst01** [comment]
Huh,

did you open a issue there ?

**Comment by jollyblade** [comment]
No, I didn't. I reverted to the influxdb-java 2.4, and everything works fine. So there is an issue then. I am not sure how to go on with it. Shall I open a new issue here?

**Comment by jollyblade** [comment]
Actually somebody else from my team upgraded to 2.5, but it wasn't in production yet. Luckily. I just realised it that it doesn't work when installing a new influxdb server.

**Comment by jollyblade** [comment]
I reopened it just to keep track of the information, so that you can decide what to do.

**Comment by majst01** [comment]
Meanwhile i updated the okhttp dependency to 3.7, please retest and report back.

**Comment by jollyblade** [comment]
Hi, Retest fine! Everything works now.

**Comment by jollyblade** [comment]
Many thanks!
