### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by mohammed-azhar** [influxdata/influxdb-java#316]
We are getting below exception while calling InfluxDb.describeDatabases(). We are using this library(version 2.4 and having jdk1.7) in our grails application, from past 2 days we are trying to figure out the cause of this issue. Can anyone please help us out here, not sure if issue in library or anything wrong with the integration.

javax.net.SocketFactory.createSocket()Ljava/net/Socket;. Stacktrace follows:
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [ping] of controller [WelcomeController]  caused exception: Runtime error executing action
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	... 7 more
Caused by: java.lang.NoSuchMethodError: javax.net.SocketFactory.createSocket()Ljava/net/Socket;
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:182)
	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:145)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:261)
	at org.influxdb.impl.InfluxDBImpl.describeDatabases(InfluxDBImpl.java:246)
	at juspay.InfluxDbService.describe(InfluxDbService.groovy:50)
	at WelcomeController$_closure8.doCall(WelcomeController.groovy:59)

Let me know if any more information needed.

**Comment by majst01** [comment]
please try with java 1.8 and influxdb-java 2.5

**Comment by mohammed-azhar** [comment]
We can't use java 1.8 as we have old built-in application using java 1.7. Any other possible solution?

**Comment by majst01** [comment]
No possible solution other than forking and use something like 
https://github.com/orfjackal/retrolambda
to convert _closure calls to something which is jav7 compatible

**Comment by mohammed-azhar** [comment]
When we execute this in standalone maven project with java 1.7 and influxdb-java 2.4 it works well. But after adding it to our project its throwing above error.

**Comment by majst01** [comment]
sorry but then it must be related to your code.
