### ISSUE TITLE
TimeUtil can not convert "yyyy-MM-dd'T'HH:mm:ssZ" to Long in Scala.

### ISSUE THREAD

**Issue by ddpaimon** [influxdata/influxdb-java#324]
When I try to do this:
```
println(TimeUtil.fromInfluxDBTimeFormat("2016-10-31T16:52:20Z") == 1477932740000L)
```
I got exception:
```
Exception in thread "main" java.lang.RuntimeException: unexpected date format
	at org.influxdb.impl.TimeUtil.fromInfluxDBTimeFormat(TimeUtil.java:88)
	at com.xxx.app$.delayedEndpoint$com$bwsw$pulse$views$app$1(xxx.scala:59)
	at com.xxx.app$delayedInit$body.apply(xxx.scala:23)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.xxx.app$.main(xxx.scala:23)
	at com.xxx.app.main(xxx.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.text.ParseException: Unparseable date: "16:52:20"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at org.influxdb.impl.TimeUtil.fromInfluxDBTimeFormat(TimeUtil.java:86)
	... 16 more
```

**Comment by fmachado** [comment]
@ddpaimon please take a look into my [comment](https://github.com/influxdata/influxdb-java/issues/339#issuecomment-311201063) and why you should avoid using TimeUtil.fromInfluxDBTimeFormat.

To fix your issue, pass a TimeUnit parameter when querying InfluxDB. If this works for you, please close this ticket.
