### ISSUE TITLE
Error Max values per tag limit exceeded InfluxDB

### ISSUE THREAD

**Issue by shashankgarimella** [influxdata/influxdb-java#357]
I am facing max values per tag limit exceeded issue when trying to write 200k points to Influx DB (version 1.2.4) through Java by specifying the batch size and poll interval in enableBatch method. I have also set max-values-per-tag = 0 in /etc/influxdb/influxdb.conf but still facing the following issue.

SEVERE: Batch could not be sent. Data will be lost
org.influxdb.InfluxDBException: {"error":"partial write: max-values-per-tag limit exceeded (100453/100000): measurement=\"samplemeasurement\" tag=\"sampletag\" value=\"samplevalue99195\" dropped=806"}
    at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:511)
    at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:312)
    at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:248)
    at org.influxdb.impl.BatchProcessor$2.run(BatchProcessor.java:278)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)

**Comment by majst01** [comment]
This error is comming from influxdb, not from the influxdb-java, so please ask this question on their repo.
