### ISSUE TITLE
Writing simple string IllegalArgumentException ERROR

### ISSUE THREAD

**Issue by renderit** [influxdata/influxdb-java#361]
Hi there, I'm having issues writing a simple json string to the influx database. I tried every permutation, but couldn;t figure it out. Any idea why? 
I have code:
```
String jsonRequest = gsonCpmpact.toJson(data);
if(jsonRequest != null) {
Point point = Point.measurement("cpu")
      .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
      .addField("used", 80L)
      .addField("sensor_val", jsonRequest)
      .tag("mytag", "test")
      .build();

   System.out.println("Empty point");
   influxDB.write(point);
}
```

And then I get output:
```
Empty point
SEVERE: Batch could not be sent. Data will be lost
java.lang.IllegalArgumentException: Expecting a non-empty string for database
        at org.influxdb.impl.Preconditions.checkNonEmptyString(Preconditions.java:22)
        at org.influxdb.dto.BatchPoints$Builder.build(BatchPoints.java:125)
        at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:232)
        at org.influxdb.impl.BatchProcessor$1.run(BatchProcessor.java:202)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

Empty point
Empty point
Empty point
```

**Comment by turetsky** [comment]
Hi, could you please check a value of the jsonRequest variable? It should not have a zero length, I guess.

**Comment by renderit** [comment]
@turetsky Hey thanks for the prompt reply.. Since its a java "string", I do check above when I do `if(jsonRequest != null) {` .. Is there something I might be missing?

**Comment by turetsky** [comment]
@renderit, welcome. You can just use `if (jsonRequest != null && jsonRequest.length > 0)` or some wraps for instance: StringUtils by Apache.

**Comment by majst01** [comment]
please show how you created the influxdb instance, the error indicates that you did not specify a database: *Expecting a non-empty string for database*

**Comment by renderit** [comment]
@majst01 In my main() I have:
```
			System.out.println("Creating database.....");
			influxDB = InfluxDBFactory.connect("http://localhost:8086", "root", "root");
			//influxDB.setConsistency()
			influxDB.createDatabase(dbName);
			// Flush every 2000 Points, at least every 1000ms
			influxDB.enableBatch(2000, 1000, TimeUnit.MILLISECONDS);

```

**Comment by renderit** [comment]
UPDATE: It seems using `influxDB.write(dbName, "autogen", point);` works! (instead of using only `influxDB.write(point)`).. Thanks @majst01 . One last aside question I had is: since I'm have fast streaming data I'm using: `influxDB.enableBatch(2000, 1000, TimeUnit.MILLISECONDS);` I want to save more data in memory before writing to disk(reducing IO) and then writing. Is it possible to do `write` asynchronously for better performance?
