### ISSUE TITLE
Unable to set "INF" retention duration

### ISSUE THREAD

**Issue by matthias-mueller** [influxdata/influxdb-java#398]
(InfluxDB 1.4 / influxdb-java 2.8)

Example 1 - Exception on overflowed duration suggests to use "INF" duration:
```java
influxDB.createRetentionPolicy("rp1", dbName, "20000w", 1, true);
```
```
Exception in thread "main" org.influxdb.InfluxDBException: {"error":"error parsing query: overflowed duration 20000w: choose a smaller duration or INF at line 1, char 56"}
```

However, it seems that "INF" is not supported by the influx java client:
```java
influxDB.createRetentionPolicy("rp1", dbName, "INF", 1, true);
```
```
Exception in thread "main" java.lang.IllegalArgumentException: Invalid InfluxDB duration: INFfor retentionDuration
	at org.influxdb.impl.Preconditions.checkDuration(Preconditions.java:47)
	at org.influxdb.impl.InfluxDBImpl.createRetentionPolicy(InfluxDBImpl.java:597)
	at org.influxdb.impl.InfluxDBImpl.createRetentionPolicy(InfluxDBImpl.java:627)
```

I think the error is in `org.influxdb.impl.Preconditions.checkDuration`. It simply doesn't check for __INF__:
```java
  public static void checkDuration(final String duration, final String name) throws IllegalArgumentException {
    if (!duration.matches("(\\d+[wdmhs])+")) {
      throw new IllegalArgumentException("Invalid InfluxDB duration: " + duration
         + "for " + name);
    }
  }
```

**Comment by fmachado** [comment]
@matthias-mueller yes, you are correct and IMHO we should `@deprecate` and *remove* methods like this. Why? Because they don't provide any real benefit: you can achieve the same result by executing a query directly.

A quick unit test:
```Java
/**
 * Test for ticket #398
 */
@Test
public void testTicket398() {
	String dbName = "ticket398_" + System.currentTimeMillis();
	influxDB.createDatabase(dbName);

	String queryString = "CREATE RETENTION POLICY \"foo\" ON " 
		+ dbName + " DURATION 23h60m REPLICATION 1 DEFAULT";
	influxDB.query(new Query(queryString, dbName));
	
	queryString = "SHOW RETENTION POLICIES ON " + dbName;
	QueryResult queryResult = influxDB.query(new Query(queryString, dbName));
	
    System.out.println("queryResult.hasError=" + queryResult.hasError());
    System.out.println("queryResult.getError=" + queryResult.getError());
    System.out.println(queryResult);

	this.influxDB.deleteDatabase(dbName);
}
```
*Output*
```
queryResult.hasError=false
queryResult.getError=null
QueryResult [results=[Result [series=[Series [name=null, tags=null, columns=[name, duration, shardGroupDuration, replicaN, default], values=[[autogen, 0s, 168h0m0s, 1.0, false], [foo, 24h0m0s, 1h0m0s, 1.0, true]]]], error=null]], error=null]
```

Could you please do it this way?

**Comment by matthias-mueller** [comment]
@fmachado I can confirm your output.

However, when I alter your query for infinite duration like this:
```java
String queryString = "CREATE RETENTION POLICY \"foo\" ON "
                + dbName + " DURATION INF REPLICATION 1 DEFAULT";
```
I cannot find any hint to an infinite retention duration in the output. Do I have to verify that duration differently?
```
queryResult.hasError=false
queryResult.getError=null
QueryResult [results=[Result [series=[Series [name=null, tags=null, columns=[name, duration, shardGroupDuration, replicaN, default], values=[[autogen, 0s, 168h0m0s, 1.0, false], [rp1, 0s, 168h0m0s, 1.0, true]]]], error=null]], error=null]
```

**Comment by matthias-mueller** [comment]
Oh now I see that INF seems to translate into "0s".

**Comment by fmachado** [comment]
@matthias-mueller I'll leave this issue open while we wait for comments on another one (already referenced here). For now I would say that we won't fix it.

**Comment by Theosakamg** [comment]
I think it's not a good choice to use a raw query (or deprecated many basic functions).

The influx-client's interest is to control/simplify usage of Influx.
A good solution was to separate dialect by version and select it when the connection is establish and version of influx is checked.

possible implementation with : https://en.wikipedia.org/wiki/Strategy_pattern
