### ISSUE TITLE
java.net.SocketException: Broken pipe (Write failed) for Influx DB  - Influx-java API

### ISSUE THREAD

**Issue by vamshireddy21** [influxdata/influxdb-java#437]
### Scenario: I have written a Kafka streams application which consumes data from an input topic, transforms data and loads into another output Kafka topic. This process is running on a thread. It continuously streams data from Kafka topic, transforms and loads to kafka topic. 

In the transform code other than transformations logic, I am also capturing the input message time(at what time the message is consumed), and output message load time(at what time it is loaded into kafka). 

And i want to write these statistics to a influx-db using Influx - Java API (in future i want to connect this influxdb to grafana and see the performance charts). before doing the batch write i am storing these points in a queue. Once the queue size gets 1000/10000(the lower you go, the longest time its taking to write) i am sending it to influx. Here is the logic 

long startTime = System.currentTimeMillis();
String statusMessage = "completed";
   ********** transformation logic  *********
long endTime = System.currentTimeMillis();

Point point = Point.measurement("name")
                               .tag("hostname", InetAddress.getLocalHost().getHostName().substring(0, 15))
			       .addField("journeySize", value.length())
                               .tag("status", statusMessage)
                               .tag("msg", value)
				.addField("response-time", (endTime - startTime)/1000)
				.build();

queue.put(point);
		 
if (queue.size() == 1000) {
	while (!(queue.isEmpty())) {
		batchPoints.point(queue.poll());
	}
	influxDB.write(batchPoints);
}

Everything was working fine small number of messages. when i increase the number of messages i am getting the below exception after some influx writes. The exception is purely because of Influx Writes.

Exception in thread "availDataTest-98090268-f5d3-419b-a4f0-813a26d93c39-StreamThread-1" org.influxdb.InfluxDBIOException: java.net.SocketException: Broken pipe (Write failed)
        at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:587)
        at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:355)
        --------- some application related stack-trace. --------------
Caused by: java.net.SocketException: Broken pipe (Write failed)
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at okio.Okio$1.write(Okio.java:79)
        at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
        at okio.RealBufferedSink.write(RealBufferedSink.java:41)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:292)
        at okio.ForwardingSink.write(ForwardingSink.java:35)
        at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:134)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
        at okio.RealBufferedSink.write(RealBufferedSink.java:91)
        at okhttp3.RequestBody$2.writeTo(RequestBody.java:98)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at org.influxdb.impl.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:143)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:579)
        ... 16 more

Just to add, I have tested the Kafka streams application( code which doesn't have influx writes) was working very good and it was performing something like 150K messages/second.

Any idea what might be causing this issue? And any fix for this issue.

**Comment by majst01** [comment]
Hi,

first of all, what version of influxdb-java are you using, i really recommend to use the most recent one because there have been a couple of changes regarding batch writes.

You dont need to care about queuing points by your own, influxdb-java has its own built-in batching mechanism, which works quite well.

You should create a single instance of a influxdb connection:

**Comment by dubsky** [comment]
Also, the code vamshireddy21 is using is not thread-safe. It may happen that the thread which is processing your code might get interrupted during queue.poll(). In such case, you might be writing the same data into Influx multiple times which is probably causing the overload.

**Comment by fmachado** [comment]
@vamshireddy21 if your issue is fixed with the help provided here, please close this issue.

**Comment by vamshireddy21** [comment]
Thanks for the clarifications. Your suggestion/idea has worked for me.
