### ISSUE TITLE
Large Result Set - Out of Memory

### ISSUE THREAD

**Issue by bhyatm** [influxdata/influxdb-java#465]
Hi,

I am querying influx db and returning a massive number of rows (2 columns - 2 MILL rows) which i then  cache into ehcahche 

The problem is when returning that amount of data if kills java heap when 
ava.lang.OutOfMemoryError: Java heap space
	at java.nio.CharBuffer.wrap(Chi arBuffer.java:373)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:211)
	at java.io.InputStreamReader.read(InputStreamReader.java:205)
	at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1263)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1005)
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:811)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.

which is part of query

Is there a way to read the result sequentially and not blow the memory stack ?

Thanks

Mac

**Comment by lxhoan** [comment]
@bhyatm 
You can try chunking query, use this method
org.influxdb.impl.InfluxDBImpl.query(final Query query, final int chunkSize, final Consumer<QueryResult> consumer)

Best,
