### ISSUE TITLE
java.net.SocketTimeoutException: Read timed out (Version 2.12)

### ISSUE THREAD

**Issue by algotradersxyz** [influxdata/influxdb-java#482]
Since I am not able to Distinct on Tags, I am using the below Query on a created Field from the tags, but as the dataset grows, the Read is timing out! Any help appreciated!

SELECT DISTINCT(3TAGS_USEDTOCREATETHISFIELD) FROM db

java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method) ~[na:na]
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:na]
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:171) ~[na:na]
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:na]
	at okio.Okio$2.read(Okio.java:139) ~[okio-1.13.0.jar:na]
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237) ~[okio-1.13.0.jar:na]
	at okio.RealBufferedSource.request(RealBufferedSource.java:67) ~[okio-1.13.0.jar:na]
	at okio.RealBufferedSource.require(RealBufferedSource.java:60) ~[okio-1.13.0.jar:na]
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:294) ~[okio-1.13.0.jar:na]
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:466) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:446) ~[okhttp-3.9.1.jar:na]
	at okio.RealBufferedSource.read(RealBufferedSource.java:46) ~[okio-1.13.0.jar:na]
	at okio.RealBufferedSource.request(RealBufferedSource.java:67) ~[okio-1.13.0.jar:na]
	at okio.RealBufferedSource.require(RealBufferedSource.java:60) ~[okio-1.13.0.jar:na]
	at okio.GzipSource.consumeHeader(GzipSource.java:114) ~[okio-1.13.0.jar:na]
	at okio.GzipSource.read(GzipSource.java:73) ~[okio-1.13.0.jar:na]
	at okio.RealBufferedSource.request(RealBufferedSource.java:67) ~[okio-1.13.0.jar:na]
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:240) ~[logging-interceptor-3.9.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.9.1.jar:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[okhttp-3.9.1.jar:na]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[okhttp-3.9.1.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) ~[na:na]

**Comment by lxhoan** [comment]
you can increase read timeout. InfluxdbImpl constructor takes a OkHttpClient.Builder instance, you can set read timeout by using OkHttpClient.Builder.readTimeout(long, TimeUnit)

**Comment by algotradersxyz** [comment]
Hey Thanks so much! This worked! I am sure lot of folks encounter both these issues so if you could please add them to Readme (might help several people)

**Comment by algotradersxyz** [comment]
Hey @lxhoan getting this error as well on trying to write async with multiple threads. Any help please

org.influxdb.InfluxDBException: timeout
	at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:154) ~[influxdb-java-2.12.jar:na]
	at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:166) ~[influxdb-java-2.12.jar:na]
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:690) ~[influxdb-java-2.12.jar:na]
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:422) ~[influxdb-java-2.12.jar:na]

**Comment by lxhoan** [comment]
you can try write timeout as well OkHttpClient.Builder.writeTimeout(long, TimeUnit)
