### ISSUE TITLE
空指针的问题

### ISSUE THREAD

**Issue by licunzhi** [influxdata/influxdb-java#488]
没有在作为依赖引入的时候直接调用connect方法然后报告空指针异常的吗？

**Comment by lxhoan** [comment]
Hi @licunzhi , could you type it in English ?

**Comment by licunzhi** [comment]
Use this project as a dependency to be added to the springboot project，However, a null pointer exception occurs when the influxdbfactory.connect () method is used in the project；Have you ever encountered this cause?
Or the first call to the class is normal, and the exception will appear when used again later
```java
java.lang.NullPointerException: null
	at okhttp3.internal.tls.BasicTrustRootIndex.<init>(BasicTrustRootIndex.java:32) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.platform.Platform.buildTrustRootIndex(Platform.java:245) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:168) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.tls.CertificateChainCleaner.get(CertificateChainCleaner.java:41) ~[okhttp-3.9.1.jar:na]
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:254) ~[okhttp-3.9.1.jar:na]
```
 thanks

**Comment by licunzhi** [comment]
Thank you ,you very 666 
Conflict with the certificate in the project
Has been resolved

**Comment by lxhoan** [comment]
you're welcome !
