### ISSUE TITLE
Error messages from server not parsed correctly when using msgpack

### ISSUE THREAD

**Issue by mschwore** [influxdata/influxdb-java#505]
I am using the new msgpack format with influxdb-java and I am not seeing the right exceptions being thrown by influxdb-java. Here's a stack trace for an exception caught by my app:

```
org.influxdb.InfluxDBException: ??error?9partial write: points beyond retention policy dropped=463
        at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:168) ~[influxdb-java-2.12.jar:?]
        at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:690) ~[influxdb-java-2.12.jar:?]
        at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:422) ~[influxdb-java-2.12.jar:?]
        at org.influxdb.impl.OneShotBatchWriter.write(OneShotBatchWriter.java:22) ~[influxdb-java-2.12.jar:?]
```
I expected to see an exception of type PointsBeyondRetentionPolicyException. It looks like the InfluxDBException class is attempting to parse the error message from influxdb-server as JSON and failing as influxdb-server is sending back a msgpack formatted error message.

Here I am just using the OneShotBatchWriter, but I imagine if you used the retry batch writer that the retry capability will be broken.

**Comment by mschwore** [comment]
This was using influxdb-java 2.12, influxdb-server 1.6.2 on CentOS 7

**Comment by majst01** [comment]
@mschwore can we close this issue ?
