### ISSUE TITLE
InfluxDBResultMapper Can not set java.time.Instant field to POJO 

### ISSUE THREAD

**Issue by liujingsheng** [influxdata/influxdb-java#540]
Hi all,
I use the influxDBResultMapper, but some times will shows error like this.
I restart the program will be good, but run for a while it will shows the error:
my code like this, any one can help to check what's wrong.

Can not set java.time.Instant field com.mango.firewaters.controllor.poco.Count.time to com.mango.firewaters.controllor.poco.Count

```Java
package com.mango.firewaters.controllor;

import com.mango.firewaters.controllor.poco.Count;
import com.mango.firewaters.controllor.poco.EventResponse;
import com.mango.firewaters.influx.InfluxRepository;
import com.mango.firewaters.influx.data.InfluxSensorDataEntity;
import com.mango.firewaters.influx.data.InfluxSensorEventEntity;
import org.influxdb.InfluxDB;
import org.influxdb.dto.BoundParameterQuery.QueryBuilder;
import org.influxdb.dto.Query;
import org.influxdb.dto.QueryResult;
import org.influxdb.impl.InfluxDBResultMapper;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.List;
import java.util.Locale;

@RestController
@RequestMapping(value = "/api/")
public class InfluxController {
    private InfluxDBResultMapper resultMapper = new InfluxDBResultMapper(); // thread-safe - can be reused
    private DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.CHINA);
    private InfluxDB influxDB;

    public InfluxController(InfluxDB influxDB) {
        this.influxDB = influxDB;

    }

    @GetMapping("/data")
    public List<InfluxSensorDataEntity> getSensorData(@RequestParam(value = "sensorid") String sensorid,
                                                      @RequestParam(value = "start", required = false, defaultValue = "") String start,
                                                      @RequestParam(value = "end", required = false, defaultValue = "") String end) {
        Query query = null;

        if (start.equals("") && end.equals("")) {
            query = QueryBuilder.newQuery("SELECT * FROM sensordata WHERE sensorid = $sensorid")
                    .forDatabase(InfluxRepository.dbName)
                    .bind("sensorid", sensorid)
                    .create();

        } else if (!start.equals("") && end.equals("")) {
            try {

                Instant startTime = dateFormat.parse(start).toInstant();
                query = QueryBuilder.newQuery("SELECT * FROM sensordata WHERE sensorid = $sensorid AND time >= $start")
                        .forDatabase(InfluxRepository.dbName)
                        .bind("sensorid", sensorid)
                        .bind("start", startTime)
                        .create();
            } catch (ParseException e) {
                e.printStackTrace();
            }


        } else if (start.equals("") && !end.equals("")) {

            try {

                Instant endTime = dateFormat.parse(end).toInstant();
                query = QueryBuilder.newQuery("SELECT * FROM sensordata WHERE sensorid = $sensorid AND time <= $end ")
                        .forDatabase(InfluxRepository.dbName)
                        .bind("sensorid", sensorid)
                        .bind("end", endTime)
                        .create();
            } catch (ParseException e) {
                e.printStackTrace();
            }

        } else if (!start.equals("") && !end.equals("")) {

            try {
                Instant startTime = dateFormat.parse(start).toInstant();
                Instant endTime = dateFormat.parse(end).toInstant();
                query = QueryBuilder.newQuery("SELECT * FROM sensordata WHERE sensorid = $sensorid AND time >= $start  AND time <= $end ")
                        .forDatabase(InfluxRepository.dbName)
                        .bind("sensorid", sensorid)
                        .bind("start", startTime)
                        .bind("end", endTime)
                        .create();
            } catch (ParseException e) {
                e.printStackTrace();
            }


        }

        QueryResult results = influxDB.query(query);

        return resultMapper.toPOJO(results, InfluxSensorDataEntity.class);

    }

    @GetMapping("/event")
    public EventResponse getSensorEvent(@RequestParam(value = "sort") String sort,@RequestParam(value = "perpage") String perpage, @RequestParam(value = "page") String page) {

        int itemsPerPage = Integer.parseInt(perpage.trim());
        int pageNumber = Integer.parseInt(page.trim());

        Query query = QueryBuilder.newQuery("SELECT COUNT(value) FROM sensorevent")
                .forDatabase(InfluxRepository.dbName)
                .create();

        QueryResult results = influxDB.query(query);
        List<Count> count = resultMapper.toPOJO(results, Count.class);
        long totalCount = count.get(0).count;
        long totalPage = (long) Math.ceil(totalCount / itemsPerPage);

        query = QueryBuilder.newQuery("select * from sensorevent order by time "+sort+" limit "+itemsPerPage+" offset "+(pageNumber*itemsPerPage))
                .forDatabase(InfluxRepository.dbName)
                .create();

        results = influxDB.query(query);
        List<InfluxSensorEventEntity> events = resultMapper.toPOJO(results, InfluxSensorEventEntity.class);

        EventResponse eventResponse=new EventResponse();
        eventResponse.setTotalCount(totalCount);
        eventResponse.setPageNumber(pageNumber);
        eventResponse.setTotalPage(totalPage);
        eventResponse.setItemsPerPage(itemsPerPage);
        eventResponse.setEvents(events);

        return eventResponse;
    }


}
```

**Comment by liujingsheng** [comment]
package com.mango.firewaters.controllor;

import com.mango.firewaters.controllor.poco.Count;
import com.mango.firewaters.controllor.poco.DashBoardData;
import com.mango.firewaters.entity.SensorRepository;
import com.mango.firewaters.influx.InfluxRepository;
import com.mango.firewaters.model.SensorState;
import org.influxdb.InfluxDB;
import org.influxdb.dto.BoundParameterQuery;
import org.influxdb.dto.Query;
import org.influxdb.dto.QueryResult;
import org.influxdb.impl.InfluxDBResultMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.Collections;
import java.util.List;

@RestController
@RequestMapping(value = "/api/dashboard/")
public class DashBoardController {

  private   InfluxDBResultMapper resultMapper = new InfluxDBResultMapper(); // thread-safe - can be reused
    @Autowired
    private SensorRepository sensorRepository;
    @Autowired
    private InfluxDB influxDB;
    @GetMapping("/tiledata")
    public DashBoardData getTileData() {

        DashBoardData dashBoardData=new DashBoardData();
        dashBoardData.setTotalSensorNum(sensorRepository.count());
        long alarmNum=sensorRepository.countByState(SensorState.SENSOR_STATE_ALARM)+sensorRepository.countByState(SensorState.SENSOR_STATE_ALARM_UP)+sensorRepository.countByState(SensorState.SENSOR_STATE_ALARM_DOWN);
        dashBoardData.setAlarmSensorNum(alarmNum);
        dashBoardData.setNormalSensorNum(dashBoardData.getTotalSensorNum()-alarmNum);
        dashBoardData.setOnlineSensorNum(sensorRepository.countByOnline(true));
        dashBoardData.setOfflineSensorNum(sensorRepository.countByOnline(false));
        Query query0 = BoundParameterQuery.QueryBuilder.newQuery("select count(sourceid) from sensorevent")
                .forDatabase(InfluxRepository.dbName)
                .create();

        QueryResult results0 = influxDB.query(query0);
        List<Count> counts = resultMapper.toPOJO(results0, Count.class);
        dashBoardData.setEventNum(counts.get(0).count);

        return dashBoardData;
    }
    @GetMapping("/monthdata")
    public  List<Count> getMonthData() {

        Query query1 = BoundParameterQuery.QueryBuilder.newQuery("select count(sourceid) from sensorevent  GROUP BY time(1d)  ORDER BY time DESC limit 7")
                .forDatabase(InfluxRepository.dbName)
                .create();

        QueryResult results1 = influxDB.query(query1);
        InfluxDBResultMapper resultMapper = new InfluxDBResultMapper(); // thread-safe - can be reused
        List<Count> counts = resultMapper.toPOJO(results1, Count.class);
        Collections.reverse(counts);
        return counts;
    }
}

**Comment by liujingsheng** [comment]
java.lang.IllegalArgumentException: Can not set java.time.Instant field com.mango.firewaters.controllor.poco.Count.time to com.mango.firewaters.controllor.poco.Count
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[na:1.8.0_172]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[na:1.8.0_172]
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[na:1.8.0_172]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:75) ~[na:1.8.0_172]
	at java.lang.reflect.Field.set(Field.java:764) ~[na:1.8.0_172]
	at org.influxdb.impl.InfluxDBResultMapper.fieldValueModified(InfluxDBResultMapper.java:331) ~[influxdb-java-2.14.jar:na]
	at org.influxdb.impl.InfluxDBResultMapper.setFieldValue(InfluxDBResultMapper.java:295) ~[influxdb-java-2.14.jar:na]
	at org.influxdb.impl.InfluxDBResultMapper.parseSeriesAs(InfluxDBResultMapper.java:246) ~[influxdb-java-2.14.jar:na]
	at org.influxdb.impl.InfluxDBResultMapper.lambda$null$2(InfluxDBResultMapper.java:179) ~[influxdb-java-2.14.jar:na]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_172]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_172]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_172]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_172]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_172]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_172]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_172]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_172]
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423) ~[na:1.8.0_172]
	at org.influxdb.impl.InfluxDBResultMapper.lambda$toPOJO$3(InfluxDBResultMapper.java:178) ~[influxdb-java-2.14.jar:na]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:1.8.0_172]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[na:1.8.0_172]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[na:1.8.0_172]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[na:1.8.0_172]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[na:1.8.0_172]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:1.8.0_172]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:1.8.0_172]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_172]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[na:1.8.0_172]
	at org.influxdb.impl.InfluxDBResultMapper.toPOJO(InfluxDBResultMapper.java:175) ~[influxdb-java-2.14.jar:na]
	at org.influxdb.impl.InfluxDBResultMapper.toPOJO(InfluxDBResultMapper.java:113) ~[influxdb-java-2.14.jar:na]
	at org.influxdb.impl.InfluxDBResultMapper.toPOJO(InfluxDBResultMapper.java:87) ~[influxdb-java-2.14.jar:na]
	at com.mango.firewaters.controllor.DashBoardController.getTileData(DashBoardController.java:45) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851) ~[spring-webmvc-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_172]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.34.jar:8.5.34]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_172]

**Comment by fmachado** [comment]
@liujingsheng can you upgrade the influxdb-java library you are using to the version 2.14 and try again? This may be related with an old bug that was fixed some time ago.

Note: not related with your original question but your REST entrypoint `/api/event` may be susceptible to SQL injection.

**Comment by liujingsheng** [comment]
@fmachado 
Thanks a lot.
I do use the version 2.14 in pom.xml, but in spring config file "application.properties"
I added a line "firewaters.influx.url=http://127.0.0.1:8086" before.
it will auto make a bean of influxdb which use the version 2.09. I think this is the root cause. may be other guy's also will have same problem.
to fix it, need make a bean not use the spring bean.

thanks for the note too.

**Comment by hamzador** [comment]
@fmachado  
Hi i have the same problem like you i tried to solve it like you sed but i steel have the same message 
    
    Request processing failed; nested exception is java.lang.IllegalArgumentException: Can not set double field org.tem.hello.entites.MemoryPoint.ValueTemperature to org.tem.hello.entites.MemoryPoint. 
could you hellp pls ?

this is my entitie :

   
 
    @Measurement(name = "temperature")
    public class MemoryPoint {
    @Column(name = "nameSensor", tag=true)
    private String nameSensor;
 
    @Column(name = "ValueTemperature")
    private double ValueTemperature;
   
    @Column(name = "date")
	private Long date;

    public MemoryPoint(String nameSensor, double valueTemperature, Long date) {
		super();
		this.nameSensor = nameSensor;
		ValueTemperature = valueTemperature;
		this.date = date;
	}

	public MemoryPoint() {
		super();
		// TODO Auto-generated constructor stub
	} 
   
    }


service:

    public List<MemoryPoint> getT() {
		
		List<MemoryPoint> memory =new ArrayList<MemoryPoint>();
		final Query query = new Query("SELECT * FROM temperature", influxDBTemplate.getDatabase());
	
		
		QueryResult queryResult = influxDBTemplate.query(query);
		InfluxDBResultMapper resultMapper = new InfluxDBResultMapper();
		
		memory =  resultMapper.toPOJO(queryResult, MemoryPoint.class);
	
		return memory;
	}




Controller:

    @RestController
    @RequestMapping( "/source")
    @CommonsLog
    public class TemperatureController {
	//@Value("${temp.url}")
	//private String url;
	
	
	@Autowired
	private TemperatureService temperatureService;


	@RequestMapping("/{userId}")
	public  List<MemoryPoint> TemperatureList(@PathVariable("userId")String userId){
		
		 List<MemoryPoint> rs=temperatureService.getT();
	
		 return rs;
		
	}

    }
application.properties
    
    server.error.whitelabel.enabled=false
    server.port=9999



    spring.influxdb.url= http://127.0.0.1:8086

    spring.influxdb.database=baeldung
    spring.influxdb.username=~
    spring.influxdb.retentionPolicy=autogen
