### ISSUE TITLE
Problem with .toPojo

### ISSUE THREAD

**Issue by MarcoOvidi** [influxdata/influxdb-java#551]
Hi ,
Java send me this error , somebody can help me 

public static void main(String[] args){
       openConnection(10,60000);  //connection with bash settings
   
      QueryResult result = influxDB.query(new Query("SELECT * FROM \"values\"","valuesStorage")); //measurements name should be quoted  in query? 

      InfluxDBResultMapper mapper = new InfluxDBResultMapper();
       List<MyValue> misure = mapper.toPOJO(result,MyValue.class);

       closeConnection();

    }

    /**
     * class mapping object on DB
     */

//TAG keys is only sensorID

    @Measurement(name = "values")
    public class MyValue {

        @Column(name = "time")
        private Instant time;

        @Column(name = "sensorID")
        private String name;

        @Column(name = "status")
        private Boolean free;

        @Column(name = "value")
        private Double used;

        @Column(name = "currentThreshold")
        private Double buffer;
    }

Query example from command line

time                                   currentThreshold sensorID    status    value
----                                   ---------------- --------         ------    -----
1547809075210000000  25.2                            1             true          23
1547809075210000000  25.2                            10           true         23
1547809075210000000  25.2                            8            true          23
1547809075210000000  25.2                            3            true          23

ERROR
Exception in thread "main" org.influxdb.InfluxDBMapperException: java.lang.InstantiationException: InfluxDB$MyValue
	at org.influxdb.impl.InfluxDBResultMapper.parseSeriesAs(InfluxDBResultMapper.java:268)
	at org.influxdb.impl.InfluxDBResultMapper.lambda$null$2(InfluxDBResultMapper.java:179)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
	at org.influxdb.impl.InfluxDBResultMapper.lambda$toPOJO$3(InfluxDBResultMapper.java:178)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.influxdb.impl.InfluxDBResultMapper.toPOJO(InfluxDBResultMapper.java:175)
	at org.influxdb.impl.InfluxDBResultMapper.toPOJO(InfluxDBResultMapper.java:113)
	at org.influxdb.impl.InfluxDBResultMapper.toPOJO(InfluxDBResultMapper.java:87)
	at InfluxDB.main(InfluxDB.java:110)
Caused by: java.lang.InstantiationException: InfluxDB$MyValue
	at java.lang.Class.newInstance(Class.java:427)
	at org.influxdb.impl.InfluxDBResultMapper.parseSeriesAs(InfluxDBResultMapper.java:244)
	... 24 more
Caused by: java.lang.NoSuchMethodException: InfluxDB$MyValue.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 25 more

**Comment by wolpl** [comment]
I was able to solve this error in one of my projects by creating a constructor with no parameters in the `MyValue` class. Do you have one?

**Comment by QuadTriangle** [comment]
[I am not a java programmer]

This is the most annoying problem I ever had. The solution was to create a new MyValue.java file instead of using a nested class.
