### ISSUE TITLE
about Annotation and addFieldsFromPOJO

### ISSUE THREAD

**Issue by kuhnwei** [influxdata/influxdb-java#586]
```
org.influxdb.InfluxDBException$UnableToParseException: unable to parse 'memory available=7660801i,buff=5024637i,free=1097692i,shared=14233360i,time=2019-04-08T07:24:18.829Z,total=16777216i,used=15679524i': invalid number

	at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:147)
	at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:173)
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:808)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:463)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:434)
	at site.mohist.influxdb.InfluxDBTest.writeMemory(InfluxDBTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

```
// about set data
memory.setTime(Instant.now());
...
// The exception comes from this line of code.
// Point.class#addFieldByAttribute#this.fields.put(fieldName, fieldValue);
Point p = Point.measurementByPOJO(memory.getClass()).addFieldsFromPOJO(memory).build();
```
First, we know that `time` must be of type `Instant` to successfully map the value of the `time` field in the query.  However, when the `time` of the Java bean is of type `Instant`, the `addFieldsFromPOJO` method cannot be used to successfully convert the `time` field

**Comment by hotdust** [comment]
addFieldsFromPOJO() is very convenient. Is there a schedule when it will be fixed?

**Comment by viliam-durina** [comment]
Seems that it's addressed in this commit added to master 5 days ago: https://github.com/influxdata/influxdb-java/commit/8d4a85371d6d876a4df96a066cb95788cf712a1f
