### ISSUE TITLE
influxdb time outside range

### ISSUE THREAD

**Issue by lwq-owesome** [influxdata/influxdb-java#626]
org.influxdb.InfluxDBException$UnableToParseException: unable to parse 'test_method amount="100",messageId="1182132790885654528",tid="bmerjurmvbanov5o9tug" 9223372036854775807': time outside range -9223372036854775806 - 9223372036854775806
	at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:147)
	at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:173)
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:796)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:455)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:430)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:408)

**Comment by majst01** [comment]
if you have timestamps larger than a 64Bit Integer, this will happen. But the question is do you plan to collect data so far in the future or in the past ?
