### ISSUE TITLE
How to use enableBatch to insert data?

### ISSUE THREAD

**Issue by GitO4Meqiquan** [influxdata/influxdb-java#631]
Hello, I am a student from china. Recently, i am working with an IOT project which uses mqtt and influxdb to collect data. And i want to insert data efficiently, so when i use mqtt client to receive data and add point to batchpoints, but i need to use method write to flush data, althought i use enableBatch().
What's more, i try to create a schedule task to write, but an exception occurred.(please forgive my poor english)
```
2019-10-30 16:36:30.007 ERROR 9324 --- [ask-scheduler-4] o.s.integration.handler.LoggingHandler   : java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.influxdb.dto.BatchPoints.lineProtocol(BatchPoints.java:331)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:455)
	at com.yinxiang.raspberry.config.ScheduleTask.configureTasks(ScheduleTask.java:43)
	at sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
**my point is using enableBatch(), how to improve insertion efficiency？**

**Comment by majst01** [comment]
Hi,
no need to excuse for poor english, im sure my chinese is way poorer :-)
As long as you use it like in https://github.com/influxdata/influxdb-java#basic-usage, there is no need for a seperate thread to write data to the database. This happens in the background in influxdb-java. Either when a specified amount of points or time has been reached, the points are written in to influxdb in one go.
You can tweak the BatchOptions for the max duration or max points until when the write should happen.

**Comment by GitO4Meqiquan** [comment]
Thanks, i have solved the problem. It turned out that I just understood it wrong :-)

**Comment by zhou5852** [comment]
的确是一个很狗屎的问题，我也遇到了 数据量还不对了 靠
