### ISSUE TITLE
Request Header Fields Too Large

### ISSUE THREAD

**Issue by piglingcn** [influxdata/influxdb-java#713]
Hello，I found this error when the sql is so long，how can i fix it ? I already set the influxdb config with "max-body-size = 0"，but problem still remains....

org.influxdb.InfluxDBException: 431 Request Header Fields Too Large
        at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:175)
        at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:796)
        at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:783)
        at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:683)
      ...

**Comment by majst01** [comment]
Hi @piglingcn 

This error message is originally comming from the influxdb database server or a webserver in front of if (if any).
Influxdb-java simply forwards the error from the database to your application.

So please consider asking this in the influxdb repo
