### ISSUE TITLE
Is there any plans to create JDBC driver? 

### ISSUE THREAD

**Issue by tjlee** [influxdata/influxdb-java#727]
It would help to work with InfluxDB more easily.

**Comment by majst01** [comment]
Hi @tjlee

I was thinking on creating a jdbc layer on top, but discarded because of no need.
I think it would be best to use influxdb-java to create a influxdb-jdbc driver

**Comment by tjlee** [comment]
>I was thinking on creating a jdbc layer on top, but discarded because of no need.
It would be helpful to access to db via 3rd party tools to see data.

**Comment by wolfig** [comment]
having a JDBC driver for InfluxDB would be beneficial I think. In the moment I am exploring how/if Liquibase can be used with InfluxDB (I want to manage continuous queries and stuff via Liquibase). As it seems, this is impossible due to the unavailability of a JDBC driver.

... however, maybe using Liquibase together with influxDB is generally a stupid idea?

**Comment by FernandoVeras** [comment]
I had the "issue". I work on a project that uses DBeaver as sql management but are CE (community) not EE (enterprise) and 'cause of this we can't connect. I just found only in enterprise.

**Comment by WaldoPepper** [comment]
It would be interesting to here, what the holdback is regarding the JDBC driver. We are currently using InfluxDB and have to move to TimescaleDB because of a need to connect via JDBC :-( sad story....

**Comment by ivan-codes-foss** [comment]
+1 re JetBrains DataGrip

**Comment by ZhenChen008** [comment]
> 

+1

**Comment by tjlee** [comment]
It looks like there is one on the market https://central.sonatype.com/artifact/org.apache.arrow/flight-sql-jdbc-driver/ . But I'm struggling with connection...

**Comment by linghengqian** [comment]
According to my test results at https://github.com/linghengqian/influxdb-3-core-jdbc-test , influxdb 3 core works perfectly with apache arrow flight sql jdbc driver. The only drawback is that influxdb 3 core stores vectors without timezone, see https://github.com/apache/arrow-java/pull/464 and https://github.com/influxdata/influxdb/issues/26581 .

**Comment by tjlee** [comment]
@linghengqian , I've run some internal tests and face an issue. 

I can't open some tables and retrieve column names due to the exception:

```
java.sql.SQLException: Error while executing SQL "SELECT t.*
FROM "system"."distinct_caches" t": Unsupported ArrowType Utf8View
at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.Helper.createException(Helper.java:56)
at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.Helper.createException(Helper.java:41)
at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:164)
at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.AvaticaStatement.execute(AvaticaStatement.java:218)
in RemoteStatementImpl.execute(RemoteStatementImpl.java:79)
Caused by: java.lang.IllegalArgumentException: Unsupported ArrowType Utf8View
at org.apache.arrow.driver.jdbc.utils.SqlTypes.getSqlTypeIdFromArrowType(SqlTypes.java:163)
at org.apache.arrow.driver.jdbc.utils.ConvertUtils.lambda$convertArrowFieldsToColumnMetaDataList$0(ConvertUtils.java:83)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:200)
at java.base/java.util.stream.Stream$1.tryAdvance(Stream.java:1469)
at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
at org.apache.arrow.driver.jdbc.utils.ConvertUtils.convertArrowFieldsToColumnMetaDataList(ConvertUtils.java:89)
at org.apache.arrow.driver.jdbc.ArrowFlightMetaImpl.newSignature(ArrowFlightMetaImpl.java:60)
at org.apache.arrow.driver.jdbc.ArrowFlightMetaImpl.prepareForHandle(ArrowFlightMetaImpl.java:175)
at org.apache.arrow.driver.jdbc.ArrowFlightMetaImpl.prepareAndExecute(ArrowFlightMetaImpl.java:209)
at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.AvaticaConnection.prepareAndExecuteInternal(AvaticaConnection.java:677)
at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:157)
at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.AvaticaStatement.execute(AvaticaStatement.java:218)
in RemoteStatementImpl.execute(RemoteStatementImpl.java:79)
... 3 more

```

**Comment by majst01** [comment]
> [@linghengqian](https://github.com/linghengqian) , I've run some internal tests and face an issue.
> 
> I can't open some tables and retrieve column names due to the exception:
> 
> ```
> java.sql.SQLException: Error while executing SQL "SELECT t.*
> FROM "system"."distinct_caches" t": Unsupported ArrowType Utf8View
> at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.Helper.createException(Helper.java:56)
> at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.Helper.createException(Helper.java:41)
> at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:164)
> at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.AvaticaStatement.execute(AvaticaStatement.java:218)
> in RemoteStatementImpl.execute(RemoteStatementImpl.java:79)
> Caused by: java.lang.IllegalArgumentException: Unsupported ArrowType Utf8View
> at org.apache.arrow.driver.jdbc.utils.SqlTypes.getSqlTypeIdFromArrowType(SqlTypes.java:163)
> at org.apache.arrow.driver.jdbc.utils.ConvertUtils.lambda$convertArrowFieldsToColumnMetaDataList$0(ConvertUtils.java:83)
> at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:200)
> at java.base/java.util.stream.Stream$1.tryAdvance(Stream.java:1469)
> at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
> at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
> at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
> at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
> at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
> at org.apache.arrow.driver.jdbc.utils.ConvertUtils.convertArrowFieldsToColumnMetaDataList(ConvertUtils.java:89)
> at org.apache.arrow.driver.jdbc.ArrowFlightMetaImpl.newSignature(ArrowFlightMetaImpl.java:60)
> at org.apache.arrow.driver.jdbc.ArrowFlightMetaImpl.prepareForHandle(ArrowFlightMetaImpl.java:175)
> at org.apache.arrow.driver.jdbc.ArrowFlightMetaImpl.prepareAndExecute(ArrowFlightMetaImpl.java:209)
> at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.AvaticaConnection.prepareAndExecuteInternal(AvaticaConnection.java:677)
> at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.AvaticaStatement.executeInternal(AvaticaStatement.java:157)
> at org.apache.arrow.driver.jdbc.shaded.org.apache.calcite.avatica.AvaticaStatement.execute(AvaticaStatement.java:218)
> in RemoteStatementImpl.execute(RemoteStatementImpl.java:79)
> ... 3 more
> ```

Please open this issue at the repo of the jdbc driver, this is not related to this repo.
