### ISSUE TITLE
Failed to get influxdb2 version

### ISSUE THREAD

**Issue by qubic** [influxdata/influxdb-java#748]
I have upgraded the influxdb server to version 2.0.6 , influxdb-java failed when evoke influxDB.query function, as it failed to get the version of influxdb2 server.
The failed exception:
```
java.lang.UnsupportedOperationException: MessagePack format is only supported from InfluxDB version 1.4 and later
	at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:820)
	at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:724)
```

**Comment by majst01** [comment]
influxdb-java is only supported with influxdb < 2.0, for newer influxdb versions you should use: https://github.com/influxdata/influxdb-client-java
