### ISSUE TITLE
Error msg so obscure when connect url port miss

### ISSUE THREAD

**Issue by camilesing** [influxdata/influxdb-java#768]
Hi, the problem takes me some time: 
when I init InfluxDB instance from `InfluxDBFactory.connect`, I miss a port, like:
~~~java
InfluxDBFactory.connect("127.0.0.1", "username", "password");
~~~
actually,  the code should be 
~~~java
InfluxDBFactory.connect("127.0.0.1:8086", "username", "password");
~~~
but I didn't notice it. then I query a table, the program throw exception and  show stack trace:
~~~java
Exception in thread "main" org.influxdb.InfluxDBException: 
	at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:175)
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:837)
	at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:824)
	at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:559)
~~~
I think its so obscure, the exception can throw early. For example, when init InfluxDB instance, it can throw `IllegalArugemntException: The port cannot be null`

**Comment by majst01** [comment]
good point, are you willing to write a fix in a pull request ?

**Comment by camilesing** [comment]
@majst01 yes, I pleasure contribute to the open-source community
