### ISSUE TITLE
Queries throw a "missing required parameter "q"" exception using influxdb-java 2.22 with enableGzip set to true

### ISSUE THREAD

**Issue by mschwore** [influxdata/influxdb-java#848]
Queries throw an exception about missing required parameter q when using the latest influxdb-java 2.22 with the enableGzip set to true. I am using influxdb-java 2.22, influxdb-server 1.8.10 on CentOS 7.

Here's my connection setup code

```
    OkHttpClient.Builder builder = new OkHttpClient.Builder().readTimeout(readTimeout, TimeUnit.SECONDS).writeTimeout(writeTimeout, TimeUnit.SECONDS);
    InfluxDB influxDB = InfluxDBFactory.connect(databaseUrl, databaseUser, databasePassword, builder, ResponseFormat.MSGPACK);
    influxDB.enableGzip();
```

This is the exception that gets thrown. My process's first query to influxdb is to create the database which this stack is for.

```
org.influxdb.InfluxDBException: missing required parameter "q"
        at org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:161) ~[influxdb-java-2.22.jar:?]
        at org.influxdb.InfluxDBException.buildExceptionForErrorState(InfluxDBException.java:189) ~[influxdb-java-2.22.jar:?]
        at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:844) ~[influxdb-java-2.22.jar:?]
        at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:833) ~[influxdb-java-2.22.jar:?]
        at org.influxdb.impl.InfluxDBImpl.createDatabase(InfluxDBImpl.java:743) ~[influxdb-java-2.22.jar:?]
```

If I leave enableGzip set to false, everything works.

**Comment by majst01** [comment]
Is this still the case with influxdb-java from master ?

**Comment by bednar** [comment]
I am to able simulate the error with actual `master` by:

```java
@Test
public void checkMissingQueryParameter() {
    OkHttpClient.Builder builder = new OkHttpClient.Builder()
            .readTimeout(10, TimeUnit.SECONDS)
            .writeTimeout(10, TimeUnit.SECONDS);
    InfluxDB influxDB = InfluxDBFactory.connect("http://localhost:8086", builder);
    influxDB.enableGzip();

    influxDB.createDatabase("my-db-test");
}
```

**Comment by bednar** [comment]
The InfluxDB 1.8 only supports HTTP Body GZIP compression for `/write` endpoint. For more info see:

- https://github.com/influxdata/influxdb/blob/d01ea614650b8682e9f3097115333c380981ad93/services/httpd/handler.go#L1588
- https://github.com/influxdata/influxdb/blob/d01ea614650b8682e9f3097115333c380981ad93/services/httpd/handler.go#L571
