### ISSUE TITLE
Cannot perform Batch write

### ISSUE THREAD

**Issue by pongo710** [influxdata/influxdb-java#95]
When i try to use the influxdb-java-api in batch mode i get an Exception.
It seems to be n bug, since i see no other possibility to use it, or am i doing something wrong.

My Code:

``` java
        InfluxDB influxDb = InfluxDBFactory.connect("host", "root", "root");
        influxDb.enableBatch(10, 1000, TimeUnit.MILLISECONDS);

        Point point = Point.measurement("test")
            .field("value", 5L)
            .time(System.currentTimeMillis(), TimeUnit.MILLISECONDS)
            .build();

        for (int i = 0; i < 100; i++) {
            influxDb.write("indy", "default", point);
        }
```

The Exception:

```
java.lang.NullPointerException
    at org.influxdb.impl.TimeUtil.toTimePrecision(TimeUtil.java:21)
    at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:155)
    at org.influxdb.impl.BatchProcessor.write(BatchProcessor.java:164)
    at org.influxdb.impl.BatchProcessor.put(BatchProcessor.java:179)
    at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:136)
    at net.contargo.imtis.monitoring.PerformanceStatsUnitTest.name(PerformanceStatsUnitTest.java:32)
```

**Comment by pongo710** [comment]
I just saw this Issue: #91 Probably its the same behaviour.

**Comment by pongo710** [comment]
@majs01 Is this issue fixed, or did you just close it?

**Comment by majst01** [comment]
I think its fixed, please use the most recent version and retest
